### ISSUE TITLE
Data source listing is breaking when adding logo image

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/data-space-portal#76]
Reference image: 

![image](https://github.com/decentralised-dataexchange/data-space-portal/assets/16397960/dea84e81-735c-497f-9739-05a9bc0c5baa)

**Comment by Karthikcs1093** [comment]
@georgepadayatti issue fixed please check with bigger images and let me know

**Comment by georgepadayatti** [comment]
> @georgepadayatti issue fixed please check with bigger images and let me know

Checked and the above issue is fixed. 

Can we centre the image and adjust the border-radius to make it look like a circle as we see in Getting Started page ?

![image](https://github.com/decentralised-dataexchange/data-space-portal/assets/16397960/ebc40b78-2749-48be-88a1-6ce0b330180b)
